// Generated by gencpp from file tle493dw2b6_nano_processor/MagneticFieldVector.msg
// DO NOT EDIT!


#ifndef TLE493DW2B6_NANO_PROCESSOR_MESSAGE_MAGNETICFIELDVECTOR_H
#define TLE493DW2B6_NANO_PROCESSOR_MESSAGE_MAGNETICFIELDVECTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tle493dw2b6_nano_processor
{
template <class ContainerAllocator>
struct MagneticFieldVector_
{
  typedef MagneticFieldVector_<ContainerAllocator> Type;

  MagneticFieldVector_()
    : header()
    , magnetic_x(0.0)
    , magnetic_y(0.0)
    , magnetic_z(0.0)  {
    }
  MagneticFieldVector_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , magnetic_x(0.0)
    , magnetic_y(0.0)
    , magnetic_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _magnetic_x_type;
  _magnetic_x_type magnetic_x;

   typedef float _magnetic_y_type;
  _magnetic_y_type magnetic_y;

   typedef float _magnetic_z_type;
  _magnetic_z_type magnetic_z;





  typedef boost::shared_ptr< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> const> ConstPtr;

}; // struct MagneticFieldVector_

typedef ::tle493dw2b6_nano_processor::MagneticFieldVector_<std::allocator<void> > MagneticFieldVector;

typedef boost::shared_ptr< ::tle493dw2b6_nano_processor::MagneticFieldVector > MagneticFieldVectorPtr;
typedef boost::shared_ptr< ::tle493dw2b6_nano_processor::MagneticFieldVector const> MagneticFieldVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator1> & lhs, const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.magnetic_x == rhs.magnetic_x &&
    lhs.magnetic_y == rhs.magnetic_y &&
    lhs.magnetic_z == rhs.magnetic_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator1> & lhs, const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tle493dw2b6_nano_processor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ed7580cb167c0fe0e989bba0b86dd98";
  }

  static const char* value(const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ed7580cb167c0feULL;
  static const uint64_t static_value2 = 0x0e989bba0b86dd98ULL;
};

template<class ContainerAllocator>
struct DataType< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tle493dw2b6_nano_processor/MagneticFieldVector";
  }

  static const char* value(const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 magnetic_x\n"
"float32 magnetic_y\n"
"float32 magnetic_z\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.magnetic_x);
      stream.next(m.magnetic_y);
      stream.next(m.magnetic_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagneticFieldVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tle493dw2b6_nano_processor::MagneticFieldVector_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "magnetic_x: ";
    Printer<float>::stream(s, indent + "  ", v.magnetic_x);
    s << indent << "magnetic_y: ";
    Printer<float>::stream(s, indent + "  ", v.magnetic_y);
    s << indent << "magnetic_z: ";
    Printer<float>::stream(s, indent + "  ", v.magnetic_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TLE493DW2B6_NANO_PROCESSOR_MESSAGE_MAGNETICFIELDVECTOR_H
